[package]
name = "ascom-fake-ccd"
version = "0.1.0"
edition = "2024"

[dependencies]
ascom-alpaca = { version = "1.0.0-beta.6", features = ["camera", "server"] }
async-trait = "0.1.89"
eyre = "0.6.12"
tokio = { version = "1.47.1", features = ["rt-multi-thread"] }
